apiVersion: v1
kind: Pod
metadata:
  name: dns-pod
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: praqma/network-multitool
      name: debug-network-container
  dnsPolicy: Default
