apiVersion: v1
kind: Pod
metadata:
  name: demo-fargate
  namespace: fargate
spec:
  containers:
  - image: nginx
    name: test-prestop
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh","-c","sleep 120"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
